config/routes.rb
Rails.application.routes.draw do
  resources :articles
  ###Edits from tutorial :
  #this routes to app/controllers/application_controller.rb <- ruby expects the 
  #"_controller.rb", that part doesn't need to be specified. We then define a method
  #within that file to handle the request. the #hello refers to the specific method. 
  root 'pages#home'

  #GET request to the about page; this is a static page so we'll use the pages controller as defined by the to line
  get 'about', to: 'pages#about'

  ###This was provided at launch: 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  get 'signup', to: 'users#new'
  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user

    validates :title, presence: true, length: {minimum: 6, maximum:100}
    validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/models/user.rb
class User <ApplicationRecord
    before_save {self.email = email.downcase}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    has_many :articles

    validates :username, presence: true, 
                      uniqueness: { case_sensitive: false }
  
    validates :email, presence: true, 
                      uniqueness: { case_sensitive: false },
                      format: { with: VALID_EMAIL_REGEX }
    
    has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [ :show, :edit, :update, :destroy ]
  
  # GET /articles or /articles.json
  def index
    @articles = Article.paginate(page: params[:page], per_page: 6)
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = User.first

      if @article.save
        flash[:notice]=  "Article was successfully created." 
        redirect_to article_path(@article) 
      else
       render 'new', status: :unprocessable_entity 
        
      end
    
  end

 
  def update
    if @article.update(article_params)
      flash[:notice]="Article was updated successfully."
      redirect_to @article
    else 
      render 'edit'
    end
  end 

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy!

    respond_to do |format|
      format.html { redirect_to articles_path, status: :see_other, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.expect(article: [ :title, :description ])
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            flash[:notice]="Welcome to ALPHABLOG, #{@user.username}! You have successfully signed up"
            redirect_to articles_path
        else
            render 'new'
        end 
    end 

    def edit 
        @user = User.find(params[:id])
    end 

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:notice] = "Your account information was succesfully updated"
            redirect_to @user
        else 
            render 'edit'
        end 
    end 

    def show
        @user = User.find(params[:id])
        @articles = @user.articles.paginate(page: params[:page], per_page: 5)
    end

    def index
        @users = User.paginate(page: params[:page], per_page: 5)
    end

    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">

<h2 class="text-center mt-4"><%=@article.title %> </h2>
 
<h1 class="text-center mt-4">Articles</h1>
<div class="container"> 
<div id="articles">
  
    <div class="col-8 mt-4">
    <div class="card text-center shadow mb-5 bg-white rounded">
  <div class="card-header font-italic">
    By <%= link_to @article.user.username, user_path(@article.user) %>
  </div>
  <div class="card-body">
     <div class="card-text text-start"><%= simple_format(@article.description) %>.</div>
   
    <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-secondary" %>
<%= link_to "Delete", article_path(@article), class:"btn btn-outline-warning", method: :delete, data: {confirm: "Are you sure?"} %>
  </div>
  <div class="card-footer text-muted">
    <small>Created <%= time_ago_in_words(@article.created_at) %> ago, edited <%= time_ago_in_words(@article.updated_at) %> ago. </small>
  </div>
</div>
</div>
   

  </div>
</div>

</div>

app/views/articles/_article_mini.html.erb
<div class="container">
    <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
            <div class="card text-center shardow mb-5 rounded">
                <div class="card-header font-italic">
                    <%= link_to article.user.username, user_path(article.user)  %>
                </div>

                <div class="card-body">
                    <h3 class="card-title"><%= link_to article.title, article_path(article) %></h3>
                    <p class="card-text"><%= truncate(article.description, length: 100)%></p>
                    <%= link_to "View", article_path(article), class:"btn btn-outline-primary" %>
                    <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-secondary" %>
                    <%= link_to "Delete", article_path(article), class:"btn btn-outline-warning", method: :delete, data: {confirm: "Are you sure?"} %>
                </div>

                <div class="card-footer text-muted">
                    <small>Created <%= time_ago_in_words(article.created_at) %> ago, edited <%= time_ago_in_words(article.updated_at) %> ago. </small>
                </div>
            </div>
        </div>
    </div>
    <% end %>
</div>

app/views/articles/_form.html.erb
 



  <div class="row justify-content-center">
  <div class="col-10">
  <%= render 'shared/errors', obj: @article %>
  <%= form_with(model: article, class:"shadow p-3 mb-5 bg-white rounded", local:true) do |form| %>
    <div class="form-group-row">
  <div class="col-2">
    <%= form.label :title, class: "col-form-label" %>
    </div>
    <div class="col-10">
    <%= form.text_field :title, class: "form-control" %>
    </div>
  </div>

  <div class="form-group-row">
  <div class="col-2">
    <%= form.label :description, class: "col-form-label" %>
    </div>
    <div class="col-10">
    <%= form.textarea :description, rows:10, class:"form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.submit class:"btn btn-outline-primary"%>
  </div>

  

  
<% end %>
  <%= link_to "Back to articles", articles_path, class: "link-primary" %>

</div>
</div>

app/views/articles/edit.html.erb
<% content_for :title, "Editing article" %>

<h1 class="text-center mt-4">Editing article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<% content_for :title, "Articles" %>

<h1 class="text-center mt-4">Articles</h1>
<div class="flickr_pagination d-flex justify-content-center">
  <%= will_paginate @articles %>
</div>
<div class="container"> 
  <div id="articles" >
  <%= render 'article_mini' %> 
  </div>
</div>

<div class="flickr_pagination d-flex justify-content-center mb-5">
  <%= will_paginate @articles %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">New article</h1>


<%= render "form", article: @article %>

app/views/articles/show.html.erb
<%= render @article %>

<div>
  <%= link_to "Back to articles", articles_path %>

 </div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="fixed-bottom footer mt-auto py-4 bg-dark text-white-50">
<div class="container text-center">
<small>Copyright &copy; 2025 <small id="logo">ALPHABLOG</small></small>
</div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
<% flash.each do |name, msg| %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
  <%= msg %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>
</div>

app/views/layouts/_navbar.html.erb
 <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "ALPHABLOG", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Articles", articles_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Bloggers", users_path, class: "nav-link" %>
        </li>
        
        <li class="nav-item"> <%= link_to "New Article", new_article_path, class: "nav-link" %> </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Udemy Course" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="d=flex flex-column">
  <%= render 'layouts/navbar' %>
  <div id="page-content" class="pb-5 mb-5">
    
    <%= render 'layouts/messages' %>
    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    
   
  </body>
</html>

app/views/pages/about.erb
<h1>This is the about page </h1>

app/views/pages/home.erb
 <div class="container-lg text-center" id="jumbotron">
 
    <h1 class="display-5 fw-bold" id="logo">ALPHABLOG </h1>
    <p class="col fs-4">A light-weight blogging app developped with Ruby on Rails following <a href="https://www.udemy.com/course/the-complete-ruby-on-rails-developer-course/">The Complete Ruby on Rails Tutorial</a> on Udemy.</p>

    <%=link_to "Sign up!", signup_path, class:"btn btn-success btn-lg" %>
</div> 

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>

<div class="alert alert-danger alert-dismissible fade show" role="alert">
 <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved: </h4>
      
 
    <ul>
    <% obj.errors.each do |error| %>
        <li><%= error.full_message %></li>
    <% end %>
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  
</div>
<% end %>

app/views/users/_form.html.erb
<div class="col-10">
    <%= render 'shared/errors', obj: @user %>
    <%= form_with(model: @user, class: "shadow p-3 mb-3 rounded", local:true) do |form| %>
    
    <div class="form-group-row">
        <%= form.label :username, class: "col-form-label" %>
        <div class="col-10">
            <%= form.text_field :username,  class: "form-control" , placeholder: "Enter a username"%>
        </div>
    </div>

    <div class="form-group-row">
         <%= form.label :email, class: "col-form-label" %>
        <div class="col-10">
            <%= form.text_field :email,  class: "form-control", placeholder: "Enter your email" %>
        </div>
    </div>

    <div class="form-group-row">
         <%= form.label :password, class: "col-form-label" %>
        <div class="col-10">
            <%= form.text_field :password,  class: "form-control", placeholder: "Choose a secure password" %>
        </div>
    </div>


  <div class="form-group row mt-3">
    <%= form.submit(@user.new_record? ? "Sign up" : "Update Account", class:"btn btn-outline-primary")%>
  </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Edit your profile</h1>
<%= render "form"%>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Alpha Bloggers</h1>
<div class="flickr_pagination d-flex justify-content-center">
  <%= will_paginate @users %>
</div>
<% @users.each do |user| %>
    <div class="row justify-content-md-center">
        <div class="card text-center shadow mb-5 rounded">
            <div class="card-header font-italic">
                <%= link_to user.username, user %>
            </div>

            <div class="card-body">
                <p class="card-text"><%=pluralize(user.articles.count, "article")%>
                <%= link_to "View profile", user, class: "btn btn-outline-success" %>
                <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-info" %>
                </p>
            </div>

            <div class="card-footer">
                <small>Joined <%= time_ago_in_words(user.created_at) %></small>
            </div>
        </div>
    </div>
<% end %>
<div class="flickr_pagination d-flex justify-content-center mb-5">
  <%= will_paginate @users %>
</div>

app/views/users/new.html.erb
<h1>Sign up for AlphaBlog</h1>
<%= render "form"%>

app/views/users/show.html.erb
<div class="container">
    <h1 class="text-center mt-4"><%= @user.username %>'s Profile</h1>
    <div class="text-center mt-4">
        <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %>
    </div>
    <h2 class="text-center mt-4">Articles</h2>
    <div class="flickr_pagination d-flex justify-content-center mb-5">
    <%= will_paginate @articles %>
    </div>
    <%= render 'articles/article_mini' %>
</div>

<div class="flickr_pagination d-flex justify-content-center mb-5">
  <%= will_paginate @articles %>
</div>